server.port: 8081

spring:

  application:
    name: telemetry-users

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/users

  security:
    basic:
    enabled: false

  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false