version: '3.4'

networks:
  telemetry:
    external: true

services:

  telemetry-user:
    image: IMAGE_NAME:IMAGE_TAG
    expose:
      - "8081"
    networks:
      - telemetry
    deploy:
      placement:
        constraints:
          - node.labels.auth == true
    environment:
      MONGODB_URI: CI_MONGODB_URI
