variables:
  SBT_VERSION: 0.13.16
  SBT_OPTS: -Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy

cache:
  key: sbt-cache
  untracked: true
  paths:
    - sbt-cache/.ivy/cache
    - sbt-cache/.boot
    - sbt-cache/.sbtboot
    - sbt-cache/target

stages:
  - app-build
  - app-test

app:build:
  stage: app-build
  image: hseeberger/scala-sbt
  script:
    - sbt clean compile
  tags:
    - shared

app:test:
  stage: app-test
  image: hseeberger/scala-sbt
  script:
    - sbt test
  tags:
    - shared